### ISSUE TITLE
User Dashboard Frontend

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodeTalk#36]
Desgin and code frontend for user Dashboard according to the existing design

**Comment by singhcoder694** [comment]
I would like to contribute in this under CodePeak'23. Sir please assign this to me.

**Comment by VishalIITP** [comment]
@singhcoder694 assigned it to you

**Comment by singhcoder694** [comment]
<img width="959" alt="Screenshot 2023-12-16 092210" src="https://github.com/VishalIITP/CodeTalk/assets/114601400/eb3f310d-638d-4601-aff8-f013b9833cfc">
Compiled Successfully but nothing is visible on screen, what can be the reason?

**Comment by VishalIITP** [comment]
@singhcoder694 you can try again.
