### ISSUE TITLE
Login page Frontend

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodeTalk#37]
Design and Code Login Page with User ID, Password, and Google Authentication

**Comment by itsmeabhishek03** [comment]
can i work on this?

**Comment by VishalIITP** [comment]
@itsmeabhishek03 assigned the issue to you, you can start working on it and if you have any doubt you can ask it here or on discord

**Comment by itsmeabhishek03** [comment]
ok thank you @VishalIITP

**Comment by itsmeabhishek03** [comment]
Hello @VishalIITP I am working on the login page issue. My doubt is do you want me to add the login page and if the user is successfully logged in then only the application should show the first page that is rendering now after application starts right ?

**Comment by VishalIITP** [comment]
> Hello @VishalIITP I am working on the login page issue. My doubt is do you want me to add the login page and if the user is successfully logged in then only the application should show the first page that is rendering now after application starts right ?

No, If the user is not logged in they can login via clicking profile icon in the navbar.

**Comment by itsmeabhishek03** [comment]
ok got it

**Comment by itsmeabhishek03** [comment]
hey @VishalIITP there is no navbar and profile icon in main branch?

**Comment by itsmeabhishek03** [comment]
Hey @VishalIITP I have almost made the login page what about backend part?

**Comment by itsmeabhishek03** [comment]
![image](https://github.com/VishalIITP/CodeTalk/assets/104294494/6996d8ff-bf59-4037-88e3-bee7db9e1369)
![image](https://github.com/VishalIITP/CodeTalk/assets/104294494/32d66299-2484-46ce-8064-8b828471ecc0)

@VishalIITP this is how it looks can i make PR or you need any modifications ?

**Comment by VishalIITP** [comment]
@itsmeabhishek03 good work!, pull the changes and you will see  a profile icon in the navbar so after clicking on profile page you can have the login and signup box to open.
![image](https://github.com/VishalIITP/CodeTalk/assets/76230753/2a0641bb-3d5e-4ca8-895a-15bbd54f7896)

**Comment by VishalIITP** [comment]
> Hey @VishalIITP I have almost made the login page what about backend part?

Create an issue in the backend codebase and start working on it after understanding the code, you can ask anything if you don't get it.

**Comment by itsmeabhishek03** [comment]
ok got it
