### ISSUE TITLE
Navbar section for better interface

### ISSUE THREAD

**Issue by saurabhgdeshmukh** [VishalIITP/CodeTalk#38]
I think there must be  a navbar section

**Comment by VishalIITP** [comment]
@saurabhgdeshmukh would you like to work on it

**Comment by saurabhgdeshmukh** [comment]
@VishalIITP yes please assign this task to me

**Comment by VishalIITP** [comment]
@saurabhgdeshmukh I have assigned this issue to you, you can start working on it and you can ask anything if you want on discord and here as well
