### ISSUE TITLE
Add Navbar functionality

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodeTalk#41]
![image](https://github.com/VishalIITP/CodeTalk/assets/76230753/90737648-9005-43a9-96d5-570eb80cdb10)
Navbar design should be inspired by this and try to match the existing website design.
It should include:
1. Profile icon as shown in the image(on the right), which will be used for login and signup.
2. Codetalk written in the centre as shown in the image. (logo).
3.  On the left side it should contain : a)Dashboard  b)Time table  c)Leaderboard
4. Make it responsive (i.e Hamburger menu on mobile and tablets screen size).

**Comment by aindree-2005** [comment]
@VishalIITP Can I work on this?

**Comment by Albert-2** [comment]
hey @VishalIITP i would like to work on this issue please assign me

**Comment by VishalIITP** [comment]
> hey @VishalIITP i would like to work on this issue please assign me

@aindree-2005 is working on this one. I have added more issues you can check them now.
