### ISSUE TITLE
npm install instead of npm init

### ISSUE THREAD

**Issue by itsmeabhishek03** [VishalIITP/CodeTalk#43]
In **README** file it should be npm install instead of npm init can i work on this.

**Comment by singhcoder694** [comment]
Is it working on doing npm install, because I did that but it has compiled but showing blank page on that url @itsmeabhishek03

**Comment by itsmeabhishek03** [comment]
@singhcoder694 "We do not need to run 'npm init' because it already has a 'package.json' file. After executing 'npm install,' it works fine for me on localhost. If it shows a blank page for you, I suggest deleting the 'node_modules' directory first. Then, run 'npm install' again, followed by 'npm start.' If the issue persists, try refreshing the page with F5. I believe it should work after following these steps."
