### ISSUE TITLE
Suggestions for Dashboard

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodeTalk#47]
Suggest what should be included in dashboard for an online course website.
1points/good suggestion.

**Comment by aindree-2005** [comment]
My Courses, with Progress bars
My Assignments , with grades
Learning Time (with graphs)
My Activity (line plot)
Badges Earned
Payment History
Pending/Suggested Courses

**Comment by aindree-2005** [comment]
@VishalIITP these are the suggestions I had based on the Glorifire app I used during jee prep

**Comment by VishalIITP** [comment]
awarded you 5 points for this one.
