### ISSUE TITLE
UI/UX design for dashboard

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodeTalk#48]
Design UI for dashboard page according to the discussions in the design suggestion isssue.
You can use Figma or any of your preffered app.

**Comment by aindree-2005** [comment]
@VishalIITP Can I work on it? I have done UI design before

**Comment by VishalIITP** [comment]
> @VishalIITP Can I work on it? I have done UI design before

Checked the design on discord, that looks good can you share figma design. or else I can close this issue by awarding you 10 points.

**Comment by aindree-2005** [comment]
[Welcome_Name.pdf](https://github.com/VishalIITP/CodeTalk/files/13725011/Welcome_Name.pdf)
@VishalIITP I created it on Canva. Here's the design
