### ISSUE TITLE
Code frontend for Dashboard

### ISSUE THREAD

**Issue by VishalIITP** [VishalIITP/CodeTalk#49]

**Comment by Yash-Ainapure** [comment]
I would like to take this issue
Could you specify what all things I should do?

**Comment by NandishM0618** [comment]
@VishalIITP I would like to work on this issue.

**Comment by VishalIITP** [comment]
> @VishalIITP I would like to take this issue.

Assinged it to you. You can reply if you want to start working.

**Comment by Yash-Ainapure** [comment]
> > @VishalIITP I would like to take this issue.
> 
> Assinged it to you. You can reply if you want to start working.

Yes

**Comment by VishalIITP** [comment]
@Yash-Ainapure what's the progress?
