### ISSUE TITLE
[ENHANCEMENT] Too mich negitive space on the site.

### ISSUE THREAD

**Issue by nepalivai** [VishalIITP/CodeTalk#68]
There is too much space on the left and right of the site. These can be filled with better UI design of the site.
<img width="944" alt="image" src="https://github.com/VishalIITP/CodeTalk/assets/108126089/13b233a2-ae19-4440-b30b-55fe2373175b">
The image below can be taken as inspiration as it uses the negative space perfectly and we can make adjustments like adding the calendar and time on the side/register now on the bottom etc.
<img width="271" alt="image" src="https://github.com/VishalIITP/CodeTalk/assets/108126089/efc985b5-8236-4f31-a7fb-a4e02fa9f892">

**Comment by VishalIITP** [comment]
That is not blank space there is content that is fetched from backend, it will be visible after backend is hosted
